<?php
/**
 * Local Testing Configuration
 * This file is automatically generated for local XAMPP testing
 */

// Override main configuration for local testing
define('LOCAL_TESTING', true);
define('SKIP_AD_AUTH', true);

// Database Configuration (Local)
define('DB_HOST', 'localhost');
define('DB_NAME', 'mcls_db');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// Disable Active Directory for local testing
define('AD_SERVER', '');
define('AD_PORT', 389);
define('AD_DOMAIN', 'LOCAL');
define('AD_BASE_DN', '');
define('AD_USERNAME', '');
define('AD_PASSWORD', '');

// Application Configuration
define('APP_NAME', 'MCLS - Maintenance Call Logging System');
define('APP_VERSION', '1.0.0');
define('APP_DEPARTMENT', 'Department of Forestry, Fisheries and the Environment');
define('SESSION_TIMEOUT', 3600);
define('TIMEZONE', 'Africa/Johannesburg');

// Security Configuration (Local Testing)
define('ENCRYPTION_KEY', 'local-testing-key-not-secure-123456');
define('PASSWORD_MIN_LENGTH', 3); // Relaxed for testing
define('SESSION_REGENERATE_TIME', 300);

// Local test password
define('LOCAL_TEST_PASSWORD', 'test123');

// Upload Configuration
define('UPLOAD_MAX_SIZE', 5242880);
define('UPLOAD_ALLOWED_TYPES', ['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']);

// Logging Configuration
define('LOG_LEVEL', 'DEBUG');
define('LOG_FILE', __DIR__ . '/../logs/app.log');
define('AUDIT_LOG_FILE', __DIR__ . '/../logs/audit.log');

// Error Reporting (Enable for testing)
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('log_errors', 1);
ini_set('error_log', __DIR__ . '/../logs/error.log');

// Set Timezone
date_default_timezone_set(TIMEZONE);

// Session Configuration
ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_secure', 0); // Disabled for HTTP local testing
ini_set('session.use_strict_mode', 1);
ini_set('session.gc_maxlifetime', SESSION_TIMEOUT);

// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
?>